### PR TITLE
Mediathekview 14.1

### PR DESCRIPTION
**Pull request by swsnr**

### CODE REVIEW

**Comment by alex1702** [comment]
use Java jdk 21.

**Comment by swsnr** [comment]
@alex1702 Won't 22 do?  As far as I know the newer the JDK the better UI support for Linux is, thanks to Jetbrains' work...

Of course, if there are issues with 22, I can downgrade to 21.  Note though that I can't do arbitrary downgrades; flathub generally only provides LTS and latest JDK.

**Comment by alex1702** [comment]
OK, I'll ask DerReisende77 if that's possible.
If you want to use the screenshots in full resolution I would recommend them instead of the slider:
https://mediathekview.de/images/screenshots/filme_uebersicht-standardansicht.png
https://mediathekview.de/images/screenshots/download_uebersicht.png

**Comment by swsnr** [comment]
@alex1702 Thanks, I'll update the screenshot links.

As for JDK, the build just passed against 22, and the result seems to work: I installed it per above instructions from the bot, and the app starts, gets the list of movies, and I can watch one in VLC.  Didn't try a download, but why should that fail with 22?

**Comment by swsnr** [comment]
@alex1702 As such I'm inclined to merge this update with JDK 22, and if there are issues, or if the Mediathekview team insists on JDK 21, I'd just make another pull request to downgrade the JDK. 

Would that be okay?

**Comment by alex1702** [comment]
jdk 22 is ok.

**Pull request merged**
