### PR TITLE
Expose home directory

### LINKED ISSUE #7: Downloaded Files won't appear in the filesystem
Hey,
when I download Files with  the flatpak Mediathekview they dont appear in Nautilus nor in the terminal. In other Flatpak-Apps saving to the filesystem works.
I've also tried 
`sudo override --filesystem=home de.mediathekview.MediathekView`
but it doesn't change anything.

### PR DESCRIPTION
**Pull request by swsnr**
Closes #7

### CODE REVIEW

**Comment by lunaryorn** [comment]
@albert180 Would you mind to test this branch?  See the `flatpak install` command above.

Please remember to reset your overrides for MediathekView first (in Flatseal, there's a "Reset" button on the top right), to make a proper test.

Afterwards you can remove the test installation with `flatpak uninstall de.mediathekview.MediathekView`, then pick the "test" one.

**Comment by swsnr** [comment]
@albert180 Did you get a chance to test this change?

**Comment by albert180** [comment]
No, sorry unfortunately I get an 404 error using that URL

**Comment by swsnr** [comment]
Well, the temporary test build expired meanwhile.  I've triggered another one; I'd appreciate if you could test it soon, before it expires again 🙂

**Comment by albert180** [comment]
I've installed it successfully will test it this evening :)

**Comment by albert180** [comment]
I've tested it, it works fine now :)

**Pull request merged**
